/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sensors/{sensor_id}/spectrum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spectrum */
        get: operations["get_spectrum_api_v1_sensors__sensor_id__spectrum_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Spectra
         * @description Configura de forma atómica y adquiere los datos de los sensores solicitados.
         */
        post: operations["analyze_spectra_api_v1_sensors_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisRequest
         * @description Payload para iniciar una configuración y lectura atómica.
         */
        AnalysisRequest: {
            /**
             * Sensor Target
             * @description Sensor a leer, o 'Merge' para adquirir y fusionar ambos.
             * @enum {string}
             */
            sensor_target: "MS-711" | "MS-713" | "Merge";
            /**
             * Exposure Time Ms
             * @description Tiempo de exposición para la lectura (10-5000ms).
             * @default 10
             */
            exposure_time_ms: number;
        };
        /**
         * AnalysisResult
         * @description Resultado del análisis espectral combinado MS-711 + MS-713.
         */
        AnalysisResult: {
            /** @description Espectro fusionado e interpolado a 1nm de resolución */
            merged_spectrum?: components["schemas"]["SpectralData"] | null;
            /**
             * Par
             * @description Radiación Fotosintéticamente Activa (W/m²), integrada de 400 a 700nm
             */
            par: number;
            /**
             * Ppfd
             * @description Densidad de Flujo de Fotones Fotosintéticos (µmol/m²/s)
             */
            ppfd: number;
            /**
             * Illuminance
             * @description Iluminancia fotópica (lux)
             */
            illuminance: number;
            /**
             * Total Irradiance
             * @description Irradiancia total integrada sobre el rango completo (W/m²)
             */
            total_irradiance: number;
            /**
             * Applied Exposure Ms
             * @description El tiempo de exposición real usado en ms
             */
            applied_exposure_ms?: number | null;
            /**
             * Pwv Cm
             * @description Vapor de Agua Precipitable (cm) calculado por inversión empírica
             */
            pwv_cm?: number | null;
            /**
             * Aod Bands
             * @description Espesor Óptico de Aerosoles (AOD) por longitud de onda {nm: valor}
             */
            aod_bands?: Record<string, number> | null;
            /**
             * Solar Geometry
             * @description Parámetros de geometría solar (SZA, elevación, masa de aire)
             */
            solar_geometry?: {
                sza: number;
                elevation: number;
                azimuth: number;
                air_mass: number | null;
                air_mass_absolute: number | null;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SpectralData */
        SpectralData: {
            /**
             * Wavelengths
             * @description Array de longitudes de onda (nm)
             */
            wavelengths: number[];
            /**
             * Irradiance
             * @description Irradiancia espectral (W/m2/um)
             */
            irradiance: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_spectrum_api_v1_sensors__sensor_id__spectrum_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpectralData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_spectra_api_v1_sensors_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
